// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzwarjplbrhqbxxmaouv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6d2FyanBsYnJocWJ4eG1hb3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTAxNTMsImV4cCI6MjA2NzgyNjE1M30.ThY6cm_13_J8Y8hVkheKeu0q2fa5r2wJOijo-rkt2yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});